const artifactImages = {
  'adventurer': {
    'flower': require('../assets/artifacts/adventurer/flower-of-life.png'),
    'plume': require('../assets/artifacts/adventurer/plume-of-death.png'),
    'sands': require('../assets/artifacts/adventurer/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/adventurer/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/adventurer/circlet-of-logos.png'),
  },
  'archaic-petra': {
    'flower': require('../assets/artifacts/archaic-petra/flower-of-life.png'),
    'plume': require('../assets/artifacts/archaic-petra/plume-of-death.png'),
    'sands': require('../assets/artifacts/archaic-petra/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/archaic-petra/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/archaic-petra/circlet-of-logos.png'),
  },
  'berserker': {
    'flower': require('../assets/artifacts/berserker/flower-of-life.png'),
    'plume': require('../assets/artifacts/berserker/plume-of-death.png'),
    'sands': require('../assets/artifacts/berserker/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/berserker/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/berserker/circlet-of-logos.png'),
  },
  'blizzard-strayer': {
    'flower': require('../assets/artifacts/blizzard-strayer/flower-of-life.png'),
    'plume': require('../assets/artifacts/blizzard-strayer/plume-of-death.png'),
    'sands': require('../assets/artifacts/blizzard-strayer/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/blizzard-strayer/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/blizzard-strayer/circlet-of-logos.png'),
  },
  'bloodstained-chivalry': {
    'flower': require('../assets/artifacts/bloodstained-chivalry/flower-of-life.png'),
    'plume': require('../assets/artifacts/bloodstained-chivalry/plume-of-death.png'),
    'sands': require('../assets/artifacts/bloodstained-chivalry/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/bloodstained-chivalry/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/bloodstained-chivalry/circlet-of-logos.png'),
  },
  'brave-heart': {
    'flower': require('../assets/artifacts/brave-heart/flower-of-life.png'),
    'plume': require('../assets/artifacts/brave-heart/plume-of-death.png'),
    'sands': require('../assets/artifacts/brave-heart/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/brave-heart/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/brave-heart/circlet-of-logos.png'),
  },
  'crimson-witch-of-flames': {
    'flower': require('../assets/artifacts/crimson-witch-of-flames/flower-of-life.png'),
    'plume': require('../assets/artifacts/crimson-witch-of-flames/plume-of-death.png'),
    'sands': require('../assets/artifacts/crimson-witch-of-flames/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/crimson-witch-of-flames/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/crimson-witch-of-flames/circlet-of-logos.png'),
  },
  'deepwood-memories': {
    'flower': require('../assets/artifacts/deepwood-memories/flower-of-life.webp'),
    'plume': require('../assets/artifacts/deepwood-memories/plume-of-death.webp'),
    'sands': require('../assets/artifacts/deepwood-memories/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/deepwood-memories/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/deepwood-memories/circlet-of-logos.webp'),
  },
  'defender-s-will': {
    'flower': require('../assets/artifacts/defender-s-will/flower-of-life.png'),
    'plume': require('../assets/artifacts/defender-s-will/plume-of-death.png'),
    'sands': require('../assets/artifacts/defender-s-will/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/defender-s-will/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/defender-s-will/circlet-of-logos.png'),
  },
  'desert-pavilion-chronicle': {
    'flower': require('../assets/artifacts/desert-pavilion-chronicle/flower-of-life.webp'),
    'plume': require('../assets/artifacts/desert-pavilion-chronicle/plume-of-death.webp'),
    'sands': require('../assets/artifacts/desert-pavilion-chronicle/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/desert-pavilion-chronicle/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/desert-pavilion-chronicle/circlet-of-logos.webp'),
  },
  'echoes-of-an-offering': {
    'flower': require('../assets/artifacts/echoes-of-an-offering/flower-of-life.webp'),
    'plume': require('../assets/artifacts/echoes-of-an-offering/plume-of-death.webp'),
    'sands': require('../assets/artifacts/echoes-of-an-offering/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/echoes-of-an-offering/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/echoes-of-an-offering/circlet-of-logos.webp'),
  },
  'emblem-of-severed-fate': {
    'flower': require('../assets/artifacts/emblem-of-severed-fate/flower-of-life.png'),
    'plume': require('../assets/artifacts/emblem-of-severed-fate/plume-of-death.png'),
    'sands': require('../assets/artifacts/emblem-of-severed-fate/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/emblem-of-severed-fate/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/emblem-of-severed-fate/circlet-of-logos.png'),
  },
  'flower-of-paradise-lost': {
    'flower': require('../assets/artifacts/flower-of-paradise-lost/flower-of-life.webp'),
    'plume': require('../assets/artifacts/flower-of-paradise-lost/plume-of-death.webp'),
    'sands': require('../assets/artifacts/flower-of-paradise-lost/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/flower-of-paradise-lost/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/flower-of-paradise-lost/circlet-of-logos.webp'),
  },
  'gambler': {
    'flower': require('../assets/artifacts/gambler/flower-of-life.png'),
    'plume': require('../assets/artifacts/gambler/plume-of-death.png'),
    'sands': require('../assets/artifacts/gambler/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/gambler/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/gambler/circlet-of-logos.png'),
  },
  'gilded-dreams': {
    'flower': require('../assets/artifacts/gilded-dreams/flower-of-life.webp'),
    'plume': require('../assets/artifacts/gilded-dreams/plume-of-death.webp'),
    'sands': require('../assets/artifacts/gilded-dreams/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/gilded-dreams/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/gilded-dreams/circlet-of-logos.webp'),
  },
  'gladiator-s-finale': {
    'flower': require('../assets/artifacts/gladiator-s-finale/flower-of-life.png'),
    'plume': require('../assets/artifacts/gladiator-s-finale/plume-of-death.png'),
    'sands': require('../assets/artifacts/gladiator-s-finale/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/gladiator-s-finale/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/gladiator-s-finale/circlet-of-logos.png'),
  },
  'golden-troupe': {
    'flower': require('../assets/artifacts/golden-troupe/flower-of-life.webp'),
    'plume': require('../assets/artifacts/golden-troupe/plume-of-death.webp'),
    'sands': require('../assets/artifacts/golden-troupe/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/golden-troupe/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/golden-troupe/circlet-of-logos.webp'),
  },
  'heart-of-depth': {
    'flower': require('../assets/artifacts/heart-of-depth/flower-of-life.png'),
    'plume': require('../assets/artifacts/heart-of-depth/plume-of-death.png'),
    'sands': require('../assets/artifacts/heart-of-depth/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/heart-of-depth/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/heart-of-depth/circlet-of-logos.png'),
  },
  'husk-of-opulent-dreams': {
    'flower': require('../assets/artifacts/husk-of-opulent-dreams/flower-of-life.png'),
    'plume': require('../assets/artifacts/husk-of-opulent-dreams/plume-of-death.png'),
    'sands': require('../assets/artifacts/husk-of-opulent-dreams/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/husk-of-opulent-dreams/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/husk-of-opulent-dreams/circlet-of-logos.png'),
  },
  'instructor': {
    'flower': require('../assets/artifacts/instructor/flower-of-life.png'),
    'plume': require('../assets/artifacts/instructor/plume-of-death.png'),
    'sands': require('../assets/artifacts/instructor/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/instructor/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/instructor/circlet-of-logos.png'),
  },
  'lavawalker': {
    'flower': require('../assets/artifacts/lavawalker/flower-of-life.png'),
    'plume': require('../assets/artifacts/lavawalker/plume-of-death.png'),
    'sands': require('../assets/artifacts/lavawalker/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/lavawalker/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/lavawalker/circlet-of-logos.png'),
  },
  'lucky-dog': {
    'flower': require('../assets/artifacts/lucky-dog/flower-of-life.png'),
    'plume': require('../assets/artifacts/lucky-dog/plume-of-death.png'),
    'sands': require('../assets/artifacts/lucky-dog/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/lucky-dog/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/lucky-dog/circlet-of-logos.png'),
  },
  'maiden-beloved': {
    'flower': require('../assets/artifacts/maiden-beloved/flower-of-life.png'),
    'plume': require('../assets/artifacts/maiden-beloved/plume-of-death.png'),
    'sands': require('../assets/artifacts/maiden-beloved/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/maiden-beloved/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/maiden-beloved/circlet-of-logos.png'),
  },
  'marechaussee-hunter': {
    'flower': require('../assets/artifacts/marechaussee-hunter/flower-of-life.webp'),
    'plume': require('../assets/artifacts/marechaussee-hunter/plume-of-death.webp'),
    'sands': require('../assets/artifacts/marechaussee-hunter/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/marechaussee-hunter/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/marechaussee-hunter/circlet-of-logos.webp'),
  },
  'martial-artist': {
    'flower': require('../assets/artifacts/martial-artist/flower-of-life.png'),
    'plume': require('../assets/artifacts/martial-artist/plume-of-death.png'),
    'sands': require('../assets/artifacts/martial-artist/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/martial-artist/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/martial-artist/circlet-of-logos.png'),
  },
  'noblesse-oblige': {
    'flower': require('../assets/artifacts/noblesse-oblige/flower-of-life.png'),
    'plume': require('../assets/artifacts/noblesse-oblige/plume-of-death.png'),
    'sands': require('../assets/artifacts/noblesse-oblige/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/noblesse-oblige/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/noblesse-oblige/circlet-of-logos.png'),
  },
  'nymph-s-dream': {
    'flower': require('../assets/artifacts/nymph-s-dream/flower-of-life.webp'),
    'plume': require('../assets/artifacts/nymph-s-dream/plume-of-death.webp'),
    'sands': require('../assets/artifacts/nymph-s-dream/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/nymph-s-dream/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/nymph-s-dream/circlet-of-logos.webp'),
  },
  'ocean-hued-clam': {
    'flower': require('../assets/artifacts/ocean-hued-clam/flower-of-life.png'),
    'plume': require('../assets/artifacts/ocean-hued-clam/plume-of-death.png'),
    'sands': require('../assets/artifacts/ocean-hued-clam/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/ocean-hued-clam/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/ocean-hued-clam/circlet-of-logos.png'),
  },
  'pale-flame': {
    'flower': require('../assets/artifacts/pale-flame/flower-of-life.png'),
    'plume': require('../assets/artifacts/pale-flame/plume-of-death.png'),
    'sands': require('../assets/artifacts/pale-flame/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/pale-flame/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/pale-flame/circlet-of-logos.png'),
  },
  'prayers-for-destiny': {
    'circlet': require('../assets/artifacts/prayers-for-destiny/circlet-of-logos.png'),
  },
  'prayers-for-illumination': {
    'circlet': require('../assets/artifacts/prayers-for-illumination/circlet-of-logos.png'),
  },
  'prayers-for-wisdom': {
    'circlet': require('../assets/artifacts/prayers-for-wisdom/circlet-of-logos.png'),
  },
  'prayers-to-springtime': {
    'circlet': require('../assets/artifacts/prayers-to-springtime/circlet-of-logos.png'),
  },
  'resolution-of-sojourner': {
    'flower': require('../assets/artifacts/resolution-of-sojourner/flower-of-life.png'),
    'plume': require('../assets/artifacts/resolution-of-sojourner/plume-of-death.png'),
    'sands': require('../assets/artifacts/resolution-of-sojourner/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/resolution-of-sojourner/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/resolution-of-sojourner/circlet-of-logos.png'),
  },
  'retracing-bolide': {
    'flower': require('../assets/artifacts/retracing-bolide/flower-of-life.png'),
    'plume': require('../assets/artifacts/retracing-bolide/plume-of-death.png'),
    'sands': require('../assets/artifacts/retracing-bolide/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/retracing-bolide/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/retracing-bolide/circlet-of-logos.png'),
  },
  'scholar': {
    'flower': require('../assets/artifacts/scholar/flower-of-life.png'),
    'plume': require('../assets/artifacts/scholar/plume-of-death.png'),
    'sands': require('../assets/artifacts/scholar/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/scholar/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/scholar/circlet-of-logos.png'),
  },
  'shimenawa-s-reminiscence': {
    'flower': require('../assets/artifacts/shimenawa-s-reminiscence/flower-of-life.png'),
    'plume': require('../assets/artifacts/shimenawa-s-reminiscence/plume-of-death.png'),
    'sands': require('../assets/artifacts/shimenawa-s-reminiscence/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/shimenawa-s-reminiscence/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/shimenawa-s-reminiscence/circlet-of-logos.png'),
  },
  'tenacity-of-the-millelith': {
    'flower': require('../assets/artifacts/tenacity-of-the-millelith/flower-of-life.png'),
    'plume': require('../assets/artifacts/tenacity-of-the-millelith/plume-of-death.png'),
    'sands': require('../assets/artifacts/tenacity-of-the-millelith/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/tenacity-of-the-millelith/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/tenacity-of-the-millelith/circlet-of-logos.png'),
  },
  'the-exile': {
    'flower': require('../assets/artifacts/the-exile/flower-of-life.png'),
    'plume': require('../assets/artifacts/the-exile/plume-of-death.png'),
    'sands': require('../assets/artifacts/the-exile/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/the-exile/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/the-exile/circlet-of-logos.png'),
  },
  'thundering-fury': {
    'flower': require('../assets/artifacts/thundering-fury/flower-of-life.png'),
    'plume': require('../assets/artifacts/thundering-fury/plume-of-death.png'),
    'sands': require('../assets/artifacts/thundering-fury/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/thundering-fury/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/thundering-fury/circlet-of-logos.png'),
  },
  'thundersoother': {
    'flower': require('../assets/artifacts/thundersoother/flower-of-life.png'),
    'plume': require('../assets/artifacts/thundersoother/plume-of-death.png'),
    'sands': require('../assets/artifacts/thundersoother/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/thundersoother/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/thundersoother/circlet-of-logos.png'),
  },
  'tiny-miracle': {
    'flower': require('../assets/artifacts/tiny-miracle/flower-of-life.png'),
    'plume': require('../assets/artifacts/tiny-miracle/plume-of-death.png'),
    'sands': require('../assets/artifacts/tiny-miracle/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/tiny-miracle/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/tiny-miracle/circlet-of-logos.png'),
  },
  'traveling-doctor': {
    'flower': require('../assets/artifacts/traveling-doctor/flower-of-life.png'),
    'plume': require('../assets/artifacts/traveling-doctor/plume-of-death.png'),
    'sands': require('../assets/artifacts/traveling-doctor/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/traveling-doctor/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/traveling-doctor/circlet-of-logos.png'),
  },
  'vermillion-hereafter': {
    'flower': require('../assets/artifacts/vermillion-hereafter/flower-of-life.webp'),
    'plume': require('../assets/artifacts/vermillion-hereafter/plume-of-death.webp'),
    'sands': require('../assets/artifacts/vermillion-hereafter/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/vermillion-hereafter/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/vermillion-hereafter/circlet-of-logos.webp'),
  },
  'viridescent-venerer': {
    'flower': require('../assets/artifacts/viridescent-venerer/flower-of-life.png'),
    'plume': require('../assets/artifacts/viridescent-venerer/plume-of-death.png'),
    'sands': require('../assets/artifacts/viridescent-venerer/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/viridescent-venerer/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/viridescent-venerer/circlet-of-logos.png'),
  },
  'vourukasha-s-glow': {
    'flower': require('../assets/artifacts/vourukasha-s-glow/flower-of-life.webp'),
    'plume': require('../assets/artifacts/vourukasha-s-glow/plume-of-death.webp'),
    'sands': require('../assets/artifacts/vourukasha-s-glow/sands-of-eon.webp'),
    'goblet': require('../assets/artifacts/vourukasha-s-glow/goblet-of-eonothem.webp'),
    'circlet': require('../assets/artifacts/vourukasha-s-glow/circlet-of-logos.webp'),
  },
  'wanderer-s-troupe': {
    'flower': require('../assets/artifacts/wanderer-s-troupe/flower-of-life.png'),
    'plume': require('../assets/artifacts/wanderer-s-troupe/plume-of-death.png'),
    'sands': require('../assets/artifacts/wanderer-s-troupe/sands-of-eon.png'),
    'goblet': require('../assets/artifacts/wanderer-s-troupe/goblet-of-eonothem.png'),
    'circlet': require('../assets/artifacts/wanderer-s-troupe/circlet-of-logos.png'),
  },
}

export default artifactImages;